# Generated by Django 5.1 on 2024-08-24 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='children',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='menunode',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='menunode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='menus.menunode'),
        ),
    ]
